// The same tycoon stays playable on devices where WebGL is unavailable.
export class CanvasGardenWorld{
constructor(canvas,state){this.canvas=canvas;this.state=state;this.ctx=canvas.getContext('2d');if(!this.ctx)throw Error('Canvas unavailable');this.angle=Math.PI/4;this.zoom=1;this.player={rotation:{y:0},userData:{swing:0}};this.time=0;this.effects=[];this.hitTimes=new Map();this.resize();}
resize(){const r=this.canvas.getBoundingClientRect();this.W=r.width;this.H=r.height;const d=Math.min(devicePixelRatio||1,2);this.canvas.width=this.W*d;this.canvas.height=this.H*d;this.ctx.setTransform(d,0,0,d,0,0);this.scale=(this.W<650?1.1:Math.min(this.W/1040,this.H/670))*this.zoom;}
rebuild(){}
project(x,y,h=0){const c=Math.cos(this.angle),s=Math.sin(this.angle);return{x:this.ox+((x-8.5)*c-(y-7)*s)*43*this.scale,y:this.oy+((x-8.5)*s+(y-7)*c)*24*this.scale-h*28*this.scale};}
pick(clientX,clientY){const r=this.canvas.getBoundingClientRect(),x=clientX-r.left,y=clientY-r.top;const candidates=this.state.nodes.filter(n=>n.ready<=Date.now()).map(n=>{const p=this.project(n.x,n.y);return{n,p};}).sort((a,b)=>b.p.y-a.p.y);for(const{n,p}of candidates){const h=n.type==='crystal'?55:n.type==='bush'?38:32;if(Math.abs(x-p.x)<23*this.scale&&y<p.y+9*this.scale&&y>p.y-h*this.scale)return{node:n,x:n.x,y:n.y};}
const a=(x-this.ox)/(43*this.scale),b=(y-this.oy)/(24*this.scale),c=Math.cos(this.angle),s=Math.sin(this.angle);return{x:a*c+b*s+8.5,y:-a*s+b*c+7};}
screen(x,y,height=1.5){return this.project(x,y,height);}
poly(pts,c){const ctx=this.ctx;ctx.fillStyle=c;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();}
ell(x,y,rx,ry,c){const ctx=this.ctx;ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
line(pts,c,w=2){const ctx=this.ctx;ctx.strokeStyle=c;ctx.lineWidth=w;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();}
text(t,x,y,size,c='#fef8dc'){this.ctx.fillStyle=c;this.ctx.font=`600 ${size}px system-ui`;this.ctx.textAlign='center';this.ctx.fillText(t,x,y);}
flower(x,y,c){this.ell(x,y,4,4,c);this.ell(x,y,1.3,1.3,'#efd67d');}
node(n,selected,hover,reduced){const p=this.project(n.x,n.y),s=this.scale,ctx=this.ctx;ctx.save();ctx.translate(p.x,p.y);ctx.scale(s,s);this.ell(0,3,20,9,'#47663527');if(n.ready>Date.now()){this.ell(0,1,7,3,n.type==='bush'?'#83a85e':'#9cab95');ctx.restore();return;}if(n.zone>=this.state.zones)ctx.globalAlpha=.6;const h=this.hitTimes.get(n.id)||0;if(h>0&&!reduced)ctx.translate(Math.sin(h*25)*2,0);
if(n.type==='bush'){this.line([{x:0,y:0},{x:0,y:-19}],'#927148',5);this.ell(-10,-14,13,11,'#578645');this.ell(10,-16,14,12,'#74a64c');this.ell(0,-25,15,12,'#9abf5e');this.ell(-4,-29,7,5,'#b1cc7d');for(let i=0;i<3;i++)this.flower(Math.sin(i*2+n.id)*12,-17-i*4,['#f3de9e','#efcbbb','#e7e9b6'][n.id%3]);}
else if(n.type==='rock'){this.poly([{x:-21,y:0},{x:-17,y:-24},{x:-2,y:-34},{x:17,y:-24},{x:23,y:-4},{x:8,y:7}], '#8da3b1');this.poly([{x:-17,y:-24},{x:-2,y:-34},{x:17,y:-24},{x:5,y:-11},{x:-8,y:-10}],'#cad7d6');this.poly([{x:5,y:-11},{x:17,y:-24},{x:23,y:-4},{x:8,y:7}],'#9fb5bd');this.ell(-12,2,6,3,'#8aa364');}
else{for(let i=0;i<3;i++){const x=(i-1)*12,top=-35-i*8;this.poly([{x:x-7,y:2},{x:x-8,y:top+12},{x,y:top},{x:x+8,y:top+12},{x:x+6,y:3}],['#a583d8','#c1a2f0','#b397e4'][i]);this.poly([{x,y:top},{x:x+8,y:top+12},{x:x+6,y:3},{x:x+1,y:top+19}],'#e1cdff');}this.text('✧',8,-30,14);}
const hp={bush:3,rock:6,crystal:10}[n.type];if(n.hp<hp){ctx.fillStyle='#3d5b43';ctx.fillRect(-16,9,32,4);ctx.fillStyle='#ecd189';ctx.fillRect(-16,9,32*n.hp/hp,4);}if((selected?.id===n.id||hover?.id===n.id)&&n.zone<this.state.zones){ctx.strokeStyle='#fff0b6';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,3,25,11,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}
person(x,y,color,moving=false,worker=false){const p=this.project(x,y),s=this.scale,ctx=this.ctx;ctx.save();ctx.translate(p.x,p.y);ctx.scale(s,s);this.ell(0,3,11,5,'#3b584932');const bob=moving?Math.sin(this.time*14)*1.5:0;ctx.translate(0,bob);this.line([{x:-4,y:-9},{x:-4,y:0}],'#41565a',5);this.line([{x:4,y:-9},{x:4,y:0}],'#41565a',5);this.ell(0,-17,9,11,color);this.ell(0,-30,8,8,'#ffd6ab');this.ell(0,-37,13,3,'#577c5a');this.poly([{x:-7,y:-41},{x:7,y:-41},{x:8,y:-36},{x:-8,y:-36}],'#7d9c6c');this.ell(3,-30,1,1.3,'#486046');const swing=worker?Math.sin(this.time*4)*4:Math.sin((this.player.userData.swing||0)*Math.PI)*15;this.line([{x:7,y:-14},{x:14,y:-27-swing}],'#a17a48',3);this.line([{x:7,y:-28-swing},{x:21,y:-24-swing}],'#c7d5d3',4);ctx.restore();}
house(x,y,name,roof){const p=this.project(x,y),s=this.scale,ctx=this.ctx;ctx.save();ctx.translate(p.x,p.y);ctx.scale(s,s);this.ell(0,8,40,18,'#3f68462a');this.poly([{x:-30,y:-9},{x:0,y:5},{x:0,y:-35},{x:-30,y:-48}],'#c4a778');this.poly([{x:0,y:5},{x:30,y:-10},{x:30,y:-48},{x:0,y:-35}],'#f0dcb4');this.poly([{x:-38,y:-45},{x:-1,y:-68},{x:38,y:-46},{x:0,y:-23}],roof);this.poly([{x:-38,y:-45},{x:-1,y:-68},{x:0,y:-50},{x:-22,y:-36}],'#ffffff22');ctx.fillStyle='#9d7952';ctx.fillRect(5,-19,10,20);ctx.fillStyle='#a8c9c4';ctx.fillRect(-22,-27,10,10);this.text(name,0,24,9,'#43633f');ctx.restore();}
garden(){const p=this.project(9,2),s=this.scale;if(this.state.projects>=1){for(let i=0;i<3;i++){const q=this.project(7.5+i,3.4);this.ell(q.x,q.y,20*s,10*s,'#ac986e');for(let j=0;j<5;j++)this.flower(q.x+Math.sin(j*3)*13*s,q.y+Math.cos(j*3)*4*s,['#eebdc1','#f0d58f','#f6efce'][i]);}}
if(this.state.projects>=2){this.ell(p.x,p.y,32*s,16*s,'#b3c1b2');this.ell(p.x,p.y-5*s,28*s,14*s,'#d9dfd0');this.ell(p.x,p.y-7*s,21*s,10*s,'#96cfd0');this.line([{x:p.x,y:p.y-8*s},{x:p.x,y:p.y-35*s}],'#d8eee0',4*s);for(let i=0;i<4;i++)this.ell(p.x+Math.sin(this.time*3+i)*9*s,p.y-(14+i*7)*s,2*s,3*s,'#d9f1e5');}if(this.state.projects>=3)this.house(9,.2,'PAVILLON','#73926c');}
hit(n,broken){this.hitTimes.set(n.id,.35);this.player.userData.swing=1;if(broken)for(let i=0;i<15;i++)this.effects.push({x:n.x,y:n.y,h:.8,vx:(Math.random()-.5)*2,vy:(Math.random()-.5)*2,vh:1+Math.random()*2,life:.7,color:n.type==='bush'?'#bad581':n.type==='rock'?'#c6d3d4':'#d4b9ff'});}
render(dt,p,selected,hover,reduced){this.time+=dt;this.scale=(this.W<650?1.1:Math.min(this.W/1040,this.H/670))*this.zoom;this.ox=this.W*.5;this.oy=this.H*.54;if(this.W<650){const pos=this.project(p.x,p.y);this.ox+=this.W/2-pos.x;this.oy+=this.H*.5-pos.y;}const ctx=this.ctx,grad=ctx.createLinearGradient(0,0,0,this.H);grad.addColorStop(0,'#c9e0d5');grad.addColorStop(1,'#b3d5c3');ctx.fillStyle=grad;ctx.fillRect(0,0,this.W,this.H);for(let i=0;i<4;i++){const x=i*this.W*.34-40;this.poly([{x:x-90,y:this.H*.45},{x,y:20+i%2*35},{x:x+150,y:this.H*.45}],['#aac5b2','#bad0b9'][i%2]);this.poly([{x:x-23,y:74},{x,y:20+i%2*35},{x:x+25,y:84},{x:x+5,y:70}], '#eef2de88');}
// Painter ordering also follows camera rotation.
const tiles=[];for(let y=0;y<15;y++)for(let x=0;x<18;x++)tiles.push({x,y,p:this.project(x,y)});tiles.sort((a,b)=>a.p.y-b.p.y);for(const t of tiles){const z=Math.floor(t.x/6),locked=z>=this.state.zones,c=t.y>=6&&t.y<=8?locked?'#c3c7ab':'#ead7a8':locked?'#a7b89b':['#b3cf83','#bec599','#bdcdb2'][z];const corners=[this.project(t.x-.5,t.y-.5),this.project(t.x+.5,t.y-.5),this.project(t.x+.5,t.y+.5),this.project(t.x-.5,t.y+.5)];if(t.y===14||t.x===17){this.poly(corners.map(q=>({x:q.x,y:q.y+15*this.scale})),'#839c70');}this.poly(corners,c);if((t.x*7+t.y*11)%9===0&&Math.abs(t.y-7)>2&&!locked)this.ell(t.p.x,t.p.y,5*this.scale,2*this.scale,'#94b56b');}
const actors=this.state.nodes.map(n=>({depth:this.project(n.x,n.y).y,draw:()=>this.node(n,selected,hover,reduced)}));actors.push({depth:this.project(p.x,p.y).y,draw:()=>this.person(p.x,p.y,'#eab166',p.moving)});actors.push({depth:this.project(1,11).y,draw:()=>this.house(1,11,'MARKT','#cb8b67')});if(this.state.workshop)actors.push({depth:this.project(1,9).y,draw:()=>this.house(1,9,'MANUFAKTUR','#6b96a3')});actors.push({depth:this.project(9,2).y,draw:()=>this.garden()});for(let i=0;i<this.state.workers;i++){const x=Math.min(this.state.zones*6-1,2+i*3)+Math.sin(this.time*.4+i)*1.2,y=5.8+Math.cos(this.time*.4+i)*.4;actors.push({depth:this.project(x,y).y,draw:()=>this.person(x,y,['#9cbec9','#d5be85','#b3a1cc'][i],true,true)});}actors.sort((a,b)=>a.depth-b.depth).forEach(a=>a.draw());for(let z=this.state.zones;z<3;z++){const q=this.project(z*6+2,7);ctx.fillStyle='#4c6b56df';ctx.beginPath();ctx.roundRect(q.x-58*this.scale,q.y-26*this.scale,116*this.scale,34*this.scale,7);ctx.fill();this.text('🔒 '+['','Steinbruch','Kristallhöhen'][z],q.x,q.y-11*this.scale,10*this.scale);this.text((z===1?180:650)+' Münzen',q.x,q.y+2*this.scale,8*this.scale,'#f0d594');}
for(const e of this.effects){e.life-=dt;e.x+=e.vx*dt;e.y+=e.vy*dt;e.h+=e.vh*dt;e.vh-=5*dt;const q=this.project(e.x,e.y,e.h);ctx.globalAlpha=Math.min(1,e.life*3);this.ell(q.x,q.y,3*this.scale,2*this.scale,e.color);}ctx.globalAlpha=1;this.effects=this.effects.filter(e=>e.life>0);for(const[k,t]of this.hitTimes)this.hitTimes.set(k,Math.max(0,t-dt));this.player.userData.swing=Math.max(0,(this.player.userData.swing||0)-dt*6);}
}
